name: Verify Secrets

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/verify-secrets.yml'

jobs:
  verify-secrets:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check required secrets
      run: |
        echo "🔍 Checking if required secrets are configured..."
        
        MISSING_SECRETS=""
        
        if [ -z "${{ secrets.GEMINI_API_KEY }}" ]; then
          echo "❌ GEMINI_API_KEY is not set"
          MISSING_SECRETS="${MISSING_SECRETS}GEMINI_API_KEY "
        else
          echo "✅ GEMINI_API_KEY is configured"
        fi
        
        if [ -z "${{ secrets.GROQ_API_KEY }}" ]; then
          echo "❌ GROQ_API_KEY is not set"
          MISSING_SECRETS="${MISSING_SECRETS}GROQ_API_KEY "
        else
          echo "✅ GROQ_API_KEY is configured"
        fi
        
        if [ -z "${{ secrets.TAVILY_API_KEY }}" ]; then
          echo "❌ TAVILY_API_KEY is not set"
          MISSING_SECRETS="${MISSING_SECRETS}TAVILY_API_KEY "
        else
          echo "✅ TAVILY_API_KEY is configured"
        fi
        
        if [ -z "${{ secrets.LANGCHAIN_API_KEY }}" ]; then
          echo "⚠️  LANGCHAIN_API_KEY is not set (optional for deployment)"
        else
          echo "✅ LANGCHAIN_API_KEY is configured"
        fi
        
        if [ -n "$MISSING_SECRETS" ]; then
          echo ""
          echo "❌ Missing required secrets: $MISSING_SECRETS"
          echo ""
          echo "Please add these secrets in:"
          echo "Repository Settings → Secrets and variables → Actions → New repository secret"
          exit 1
        else
          echo ""
          echo "✅ All required secrets are configured!"
        fi
    
    - name: Test API connectivity
      if: success()
      run: |
        echo "🔗 Testing API connectivity..."
        
        # Test Gemini API
        if curl -s -o /dev/null -w "%{http_code}" \
          -H "Content-Type: application/json" \
          -H "x-goog-api-key: ${{ secrets.GEMINI_API_KEY }}" \
          "https://generativelanguage.googleapis.com/v1beta/models" | grep -q "200\|401"; then
          echo "✅ Gemini API key format appears valid"
        else
          echo "⚠️  Could not validate Gemini API key"
        fi
        
        echo ""
        echo "✅ Secret verification complete!"